apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: number-game-dev
  namespace: argocd
  labels:
    environment: development
spec:
  project: default
  source:
    repoURL: https://github.com/Number-Game-App/number-game-platform
    targetRevision: develop
    path: helm-chart
    helm:
      valueFiles:
        - values/development.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: number-game-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s