# Prometheus Stack Installation via ArgoCD
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  labels:
    app: prometheus-stack
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 61.1.1
    chart: kube-prometheus-stack
    helm:
      values: |
        # Simplified Prometheus configuration for Number Game
        prometheus:
          prometheusSpec:
            # Enable ServiceMonitor discovery across all namespaces
            serviceMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
            retention: 7d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: standard
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 5Gi
        
        # Grafana configuration
        grafana:
          adminPassword: admin
          service:
            type: LoadBalancer
          persistence:
            enabled: true
            size: 1Gi
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
              - name: 'number-game-dashboards'
                orgId: 1
                folder: 'Number Game'
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/number-game
        
        # AlertManager configuration
        alertmanager:
          config:
            global:
              smtp_smarthost: 'localhost:587'
            route:
              group_by: ['alertname', 'cluster', 'service']
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 12h
              receiver: 'web.hook'
              routes:
              - match:
                  alertname: NumberGameDown
                receiver: 'critical-alerts'
              - match:
                  severity: warning
                receiver: 'warning-alerts'
            receivers:
            - name: 'web.hook'
              webhook_configs:
              - url: 'http://127.0.0.1:5001/'
            - name: 'critical-alerts'
              webhook_configs:
              - url: 'http://127.0.0.1:5001/critical'
                title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
            - name: 'warning-alerts'
              webhook_configs:
              - url: 'http://127.0.0.1:5001/warning'
                title: '⚠️ Warning: {{ .GroupLabels.alertname }}'
        
        # Node exporter for infrastructure metrics
        nodeExporter:
          enabled: true
        
        # Kube-state-metrics for Kubernetes metrics
        kubeStateMetrics:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s