apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: number-game-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Number-Game-App/number-game-platform
    targetRevision: main
    path: helm-chart
    helm:
      valueFiles:
        - values/production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: number-game-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
